/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; under version 2
 * of the License (non-upgradable).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 31 Milk St # 960789 Boston, MA 02196 USA.
 *
 * Copyright (c) 2026 (original work) Open Assessment Technologies SA ;
 */
define([
    'lodash',
    'taoQtiItem/qtiItem/core/Element',
    'taoQtiItem/qtiItem/helper/response',
    'taoQtiItem/qtiCreator/helper/textEntryEvaluationHelper',
    'taoQtiItem/qtiXmlRenderer/helper/scoringModelResponseProcessingGenerator'
], function (_, Element, responseHelper, textEntryEvaluationHelper, scoringModelRpGenerator) {
    'use strict';

    const DATA_SCORING_MODEL = 'data-scoring-model';
    // Authoring-only flag: custom RP was generated by scoring model; stripped on export.
    const DATA_SCORING_MODEL_RP_MANAGED = 'data-scoring-model-rp-managed';
    const TEXT_ENTRY_QTI_CLASS = 'textEntryInteraction';
    const TEMP_SCORE_OUTCOME = scoringModelRpGenerator.DEFAULT_TEMP_SCORE_OUTCOME;
    const SCORE_OUTCOME = scoringModelRpGenerator.DEFAULT_SCORE_OUTCOME;
    const MAXSCORE_OUTCOME = 'MAXSCORE';

    const MODEL_SIMPLE_SUM = 'simpleSum';
    const MODEL_DICHOTOMOUS = 'dichotomous';
    const MODEL_POLYTOMOUS = 'polytomous';

    const DEFAULT_DICHOTOMOUS_THRESHOLD = 1;
    const DEFAULT_DICHOTOMOUS_SCORE = 1;
    const DEFAULT_POLYTOMOUS_LEVELS = [
        { threshold: 5, score: 2 },
        { threshold: 3, score: 1 }
    ];

    /**
     * @param {Object} element
     * @returns {boolean}
     */
    const isTextEntryElement = function isTextEntryElement(element) {
        if (!element) {
            return false;
        }

        if (_.isFunction(element.is)) {
            return element.is(TEXT_ENTRY_QTI_CLASS);
        }

        return Element.isA(element, TEXT_ENTRY_QTI_CLASS) || element.qtiClass === TEXT_ENTRY_QTI_CLASS;
    };

    /**
     * @param {Object} interaction
     * @returns {Object[]}
     */
    const getItemTextEntries = function getItemTextEntries(interaction) {
        return textEntryEvaluationHelper.getItemTextEntries(interaction);
    };

    /**
     * First textEntryInteraction in document order is the persistence anchor.
     *
     * @param {Object} interaction
     * @returns {Object|null}
     */
    const getPrimaryTextEntry = function getPrimaryTextEntry(interaction) {
        textEntryEvaluationHelper.migrateFeatureDataAttributesToPrimary(interaction);

        return textEntryEvaluationHelper.getPrimaryTextEntry(getItemTextEntries(interaction));
    };

    /**
     * @param {*} value
     * @returns {number|null}
     */
    const toFiniteNumber = function toFiniteNumber(value) {
        const number = Number(value);

        return _.isFinite(number) ? number : null;
    };

    /**
     * @param {Object|Array} raw
     * @returns {Object[]}
     */
    const normalizeThresholds = function normalizeThresholds(raw) {
        let pairs = [];

        if (_.isArray(raw)) {
            pairs = raw;
        } else if (_.isPlainObject(raw)) {
            pairs = _.map(raw, (score, threshold) => ({ threshold, score }));
        }

        return _(pairs)
            .map(entry => {
                const threshold = toFiniteNumber(
                    _.isPlainObject(entry) ? entry.threshold : null
                );
                const score = toFiniteNumber(_.isPlainObject(entry) ? entry.score : null);

                if (threshold === null || score === null) {
                    return null;
                }

                return { threshold, score };
            })
            .compact()
            .sortBy(entry => -entry.threshold)
            .value();
    };

    /**
     * Accepts JSON or the ticket-style single-quoted mapping.
     *
     * @param {string} raw
     * @returns {Object[]}
     */
    const parseScoringModelAttribute = function parseScoringModelAttribute(raw) {
        if (!_.isString(raw) || !raw.trim()) {
            return [];
        }

        const trimmed = raw.trim();

        try {
            return normalizeThresholds(JSON.parse(trimmed));
        } catch (e) {
            try {
                const normalized = trimmed.replace(/'/g, '"');

                return normalizeThresholds(JSON.parse(normalized));
            } catch (ignore) {
                return [];
            }
        }
    };

    /**
     * @param {Object[]} thresholds
     * @returns {string}
     */
    const serializeScoringModelAttribute = function serializeScoringModelAttribute(thresholds) {
        const mapping = {};

        _.forEach(normalizeThresholds(thresholds), entry => {
            mapping[String(entry.threshold)] = entry.score;
        });

        return JSON.stringify(mapping);
    };

    /**
     * @param {Object[]} thresholds
     * @returns {string}
     */
    const resolveModelFromThresholds = function resolveModelFromThresholds(thresholds) {
        const count = (thresholds || []).length;

        if (count >= 2) {
            return MODEL_POLYTOMOUS;
        }

        if (count === 1) {
            return MODEL_DICHOTOMOUS;
        }

        return MODEL_SIMPLE_SUM;
    };

    /**
     * @param {Object} interaction
     * @returns {{model: string, thresholds: Object[]}}
     */
    const getScoringModelConfig = function getScoringModelConfig(interaction) {
        const primary = getPrimaryTextEntry(interaction);
        const raw = primary && _.isFunction(primary.attr) ? primary.attr(DATA_SCORING_MODEL) : null;
        const thresholds = parseScoringModelAttribute(raw);

        return {
            model: resolveModelFromThresholds(thresholds),
            thresholds
        };
    };

    /**
     * @param {string} model
     * @param {Object[]} [thresholds]
     * @returns {Object[]}
     */
    const ensureThresholdsForModel = function ensureThresholdsForModel(model, thresholds) {
        const normalized = normalizeThresholds(thresholds);

        if (model === MODEL_DICHOTOMOUS) {
            if (normalized.length) {
                return [normalized[0]];
            }

            return [
                {
                    threshold: DEFAULT_DICHOTOMOUS_THRESHOLD,
                    score: DEFAULT_DICHOTOMOUS_SCORE
                }
            ];
        }

        if (model === MODEL_POLYTOMOUS) {
            if (normalized.length >= 2) {
                return normalized;
            }

            if (normalized.length === 1) {
                return [normalized[0], _.clone(DEFAULT_POLYTOMOUS_LEVELS[1])];
            }

            return _.map(DEFAULT_POLYTOMOUS_LEVELS, _.clone);
        }

        return [];
    };

    /**
     * @param {Object} interaction
     * @returns {string[]}
     */
    const getTextEntryResponseIdentifiers = function getTextEntryResponseIdentifiers(interaction) {
        return textEntryEvaluationHelper.getTextEntryResponseIdentifiers(interaction);
    };

    /**
     * Keep map-response templates so authoring UI stays on "map response"
     * while scoring-model RP is stored as custom XML.
     *
     * @param {Object} interaction
     */
    const ensureMapResponseTemplates = function ensureMapResponseTemplates(interaction) {
        _.forEach(getItemTextEntries(interaction), textEntry => {
            const response = _.isFunction(textEntry.getResponseDeclaration)
                ? textEntry.getResponseDeclaration()
                : null;

            if (!response || !_.isFunction(response.setTemplate)) {
                return;
            }

            if (
                responseHelper.isUsingTemplate(response, 'MAP_RESPONSE') ||
                responseHelper.isUsingTemplate(response, 'MAP_RESPONSE_POINT')
            ) {
                return;
            }

            response.setTemplate('MAP_RESPONSE');
        });
    };

    /**
     * Apply custom RP XML without flipping response templates via setProcessingType.
     * Dichotomous/polytomous still need map-response UI (map entries) while RP is custom.
     *
     * @param {Object} item
     * @param {string} xml
     */
    const updateCustomResponseProcessing = function updateCustomResponseProcessing(item, xml) {
        const rp = item && item.responseProcessing;

        if (!rp || !_.isString(xml) || !xml.trim()) {
            return;
        }

        rp.processingType = 'custom';
        rp.xml = xml;
    };

    /**
     * @param {Object} item
     */
    const restoreTemplateDrivenResponseProcessing = function restoreTemplateDrivenResponseProcessing(item) {
        const rp = item && item.responseProcessing;

        if (!rp) {
            return;
        }

        // Avoid setProcessingType('templateDriven') — it resets every response to MATCH_CORRECT.
        rp.processingType = 'templateDriven';
        rp.xml = '';
    };

    /**
     * @param {Object} item
     * @param {string} identifier
     * @param {Object} attributes
     * @param {number|null} [defaultValue]
     * @returns {Object|null}
     */
    const ensureOutcomeDeclaration = function ensureOutcomeDeclaration(item, identifier, attributes, defaultValue) {
        if (!item || !_.isFunction(item.getOutcomeDeclaration) || !_.isFunction(item.createOutcomeDeclaration)) {
            return null;
        }

        let outcome = item.getOutcomeDeclaration(identifier);

        if (!outcome) {
            outcome = item.createOutcomeDeclaration(_.clone(attributes));
            if (_.isFunction(outcome.buildIdentifier)) {
                outcome.buildIdentifier(identifier, false);
            }
        }

        if (!_.isUndefined(defaultValue) && _.isFunction(outcome.setDefaultValue)) {
            outcome.setDefaultValue(defaultValue);
        }

        return outcome;
    };

    /**
     * @param {Object} item
     * @param {number} maxScore
     */
    const syncOutcomeDeclarations = function syncOutcomeDeclarations(item, maxScore) {
        const tempScore = ensureOutcomeDeclaration(
            item,
            TEMP_SCORE_OUTCOME,
            {
                cardinality: 'single',
                baseType: 'float'
            },
            0
        );

        if (tempScore && _.isFunction(tempScore.attr)) {
            tempScore.attr('normalMinimum', 0);
        }

        const scoreOutcome = ensureOutcomeDeclaration(
            item,
            SCORE_OUTCOME,
            {
                cardinality: 'single',
                baseType: 'float'
            },
            0
        );

        if (scoreOutcome && _.isFunction(scoreOutcome.attr)) {
            scoreOutcome.attr('normalMinimum', 0);
            scoreOutcome.attr('normalMaximum', maxScore);
        }

        const maxScoreOutcome = ensureOutcomeDeclaration(
            item,
            MAXSCORE_OUTCOME,
            {
                cardinality: 'single',
                baseType: 'float'
            },
            maxScore
        );

        if (maxScoreOutcome && _.isFunction(maxScoreOutcome.setDefaultValue)) {
            maxScoreOutcome.setDefaultValue(maxScore);
        }
    };

    /**
     * @param {Object} item
     * @param {Object} primaryTextEntry
     */
    const clearScoringModelResponseProcessing = function clearScoringModelResponseProcessing(item, primaryTextEntry) {
        if (!item || !primaryTextEntry) {
            return;
        }

        const wasManaged = primaryTextEntry.attr(DATA_SCORING_MODEL_RP_MANAGED) === 'true';

        if (wasManaged) {
            restoreTemplateDrivenResponseProcessing(item);

            if (_.isFunction(item.removeOutcome)) {
                item.removeOutcome(TEMP_SCORE_OUTCOME);
            }

            const scoreOutcome = _.isFunction(item.getOutcomeDeclaration)
                ? item.getOutcomeDeclaration(SCORE_OUTCOME)
                : null;

            if (scoreOutcome && _.isFunction(scoreOutcome.removeAttr)) {
                scoreOutcome.removeAttr('normalMaximum');
                scoreOutcome.removeAttr('normalMinimum');
            }
        }

        if (_.isFunction(primaryTextEntry.removeAttr)) {
            primaryTextEntry.removeAttr(DATA_SCORING_MODEL_RP_MANAGED);
        }
    };

    /**
     * Build custom RP for dichotomous/polytomous models.
     * Skipped when UMFI owns custom response processing.
     *
     * @param {Object} interaction
     * @param {{model: string, thresholds?: Object[]}} config
     */
    const syncResponseProcessing = function syncResponseProcessing(interaction, config) {
        const item = interaction && _.isFunction(interaction.getRootElement) ? interaction.getRootElement() : null;
        const primary = getPrimaryTextEntry(interaction);
        const model = (config && config.model) || MODEL_SIMPLE_SUM;

        if (!item || !primary) {
            return;
        }

        // UMFI owns custom RP. Rebuild so data-scoring-model thresholds are applied
        // (or cleared) inside the synonym-group response processing.
        if (textEntryEvaluationHelper.isUmfiEnabled(interaction)) {
            textEntryEvaluationHelper.syncResponseProcessing(interaction, {
                evaluateAsUmfi: true,
                lexicalGroups: textEntryEvaluationHelper.getLexicalGroups(interaction)
            });
            return;
        }

        if (model === MODEL_SIMPLE_SUM) {
            clearScoringModelResponseProcessing(item, primary);
            return;
        }

        const thresholds = ensureThresholdsForModel(model, config && config.thresholds);
        const interactions = getTextEntryResponseIdentifiers(interaction);

        if (!interactions.length || !thresholds.length) {
            return;
        }

        const rpConfig = scoringModelRpGenerator.normalizeConfig({
            interactions,
            thresholds
        });
        const rpXml = scoringModelRpGenerator.generateResponseProcessing(rpConfig);
        const maxScore = scoringModelRpGenerator.getMaxScore(rpConfig);

        if (!item.responseProcessing) {
            return;
        }

        updateCustomResponseProcessing(item, rpXml);
        ensureMapResponseTemplates(interaction);
        syncOutcomeDeclarations(item, maxScore);
        primary.attr(DATA_SCORING_MODEL_RP_MANAGED, 'true');
    };

    /**
     * @param {Object} interaction
     * @param {{model: string, thresholds?: Object[]}} config
     */
    const persistScoringModelConfig = function persistScoringModelConfig(interaction, config) {
        textEntryEvaluationHelper.migrateFeatureDataAttributesToPrimary(interaction);
        const primary = getPrimaryTextEntry(interaction);

        if (!primary || !_.isFunction(primary.attr)) {
            return;
        }

        const model = (config && config.model) || MODEL_SIMPLE_SUM;

        if (model === MODEL_SIMPLE_SUM) {
            if (_.isFunction(primary.removeAttr)) {
                primary.removeAttr(DATA_SCORING_MODEL);
            } else {
                primary.attr(DATA_SCORING_MODEL, null);
            }

            syncResponseProcessing(interaction, { model: MODEL_SIMPLE_SUM, thresholds: [] });
            return;
        }

        const thresholds = ensureThresholdsForModel(model, config && config.thresholds);

        primary.attr(DATA_SCORING_MODEL, serializeScoringModelAttribute(thresholds));
        syncResponseProcessing(interaction, { model, thresholds });
    };

    /**
     * Re-apply persisted scoring-model RP before save when needed.
     *
     * @param {Object} item
     */
    const ensurePersistedBeforeSave = function ensurePersistedBeforeSave(item) {
        if (!item) {
            return;
        }

        const sampleInteraction = {
            getRootElement: function getRootElement() {
                return item;
            },
            qtiClass: TEXT_ENTRY_QTI_CLASS,
            is: function (qtiClass) {
                return qtiClass === TEXT_ENTRY_QTI_CLASS;
            }
        };

        textEntryEvaluationHelper.syncTextContainersFromDom(item);
        textEntryEvaluationHelper.migrateFeatureDataAttributesToPrimary(sampleInteraction);

        const primary = getPrimaryTextEntry(sampleInteraction);

        if (!primary) {
            return;
        }

        const config = getScoringModelConfig(sampleInteraction);

        if (config.model === MODEL_SIMPLE_SUM) {
            return;
        }

        persistScoringModelConfig(sampleInteraction, config);
    };

    /**
     * Visible when map-response is selected, or Unordered Multi-Field evaluation is enabled.
     *
     * @param {Object} interaction
     * @param {{evaluateAsUmfi?: boolean, responseTemplate?: string}} [options]
     * @returns {boolean}
     */
    const shouldShowScoringModel = function shouldShowScoringModel(interaction, options) {
        if (!isTextEntryElement(interaction)) {
            return false;
        }

        const response = _.isFunction(interaction.getResponseDeclaration)
            ? interaction.getResponseDeclaration()
            : null;
        const formTemplate = options && options.responseTemplate;
        const isMapResponse =
            formTemplate === 'MAP_RESPONSE' ||
            formTemplate === 'MAP_RESPONSE_POINT' ||
            (response && responseHelper.isUsingTemplate(response, 'MAP_RESPONSE')) ||
            (response && responseHelper.isUsingTemplate(response, 'MAP_RESPONSE_POINT'));

        if (isMapResponse) {
            return true;
        }

        if (options && typeof options.evaluateAsUmfi === 'boolean') {
            return options.evaluateAsUmfi;
        }

        return textEntryEvaluationHelper.isUmfiEnabled(interaction);
    };

    return {
        DATA_SCORING_MODEL,
        DATA_SCORING_MODEL_RP_MANAGED,
        TEMP_SCORE_OUTCOME,
        MODEL_SIMPLE_SUM,
        MODEL_DICHOTOMOUS,
        MODEL_POLYTOMOUS,
        DEFAULT_DICHOTOMOUS_THRESHOLD,
        DEFAULT_DICHOTOMOUS_SCORE,
        DEFAULT_POLYTOMOUS_LEVELS,
        getItemTextEntries,
        getPrimaryTextEntry,
        getTextEntryResponseIdentifiers,
        parseScoringModelAttribute,
        serializeScoringModelAttribute,
        resolveModelFromThresholds,
        normalizeThresholds,
        ensureThresholdsForModel,
        getScoringModelConfig,
        persistScoringModelConfig,
        syncResponseProcessing,
        clearScoringModelResponseProcessing,
        ensurePersistedBeforeSave,
        shouldShowScoringModel
    };
});
