/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; under version 2
 * of the License (non-upgradable).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 31 Milk St # 960789 Boston, MA 02196 USA.
 *
 * Copyright (c) 2026 (original work) Open Assessment Technologies SA ;
 */
define([
    'jquery',
    'lodash',
    'taoQtiItem/qtiItem/core/Element',
    'taoQtiItem/qtiCreator/editor/gridEditor/content',
    'taoQtiItem/qtiXmlRenderer/helper/synonymGroupResponseProcessingGenerator'
], function ($, _, Element, contentHelper, synonymGroupGenerator) {
    'use strict';

    const UMFI_ITEM_TYPE = 'umfi-closed';
    const UMFI_OPEN_ITEM_TYPE = 'umfi-open';
    const UMFI_ITEM_TYPES = [UMFI_ITEM_TYPE, UMFI_OPEN_ITEM_TYPE];
    const DATA_ITEM_TYPE = 'data-item-type';
    // Public lexical-group payload kept in saved item XML:
    // [{ group: "GROUP_1_FOUND", canonical: "Apple", variants: ["Apple", ...] }]
    // `group` matches the response-processing / outcome identifier (*_FOUND).
    const DATA_UMFI_VALUES = 'data-umfi-values';
    const DATA_CASE_SENSITIVE = 'data-case-sensitive';
    const DATA_ALLOW_LEXICAL_FIELDS = 'data-allow-lexical-fields-on-scoring';
    // Live-editor checklist of UMFI-created *_FOUND outcome ids (e.g. ["APPLE_FOUND"]).
    // Used to remove stale outcomes when groups change or UMFI is disabled.
    // Regenerated from data-umfi-values on open/sync; stripped from exported XML.
    const DATA_MANAGED_OUTCOMES = 'data-umfi-managed-outcomes';
    // Marks that custom responseProcessing was generated by UMFI; stripped from exported XML.
    const DATA_RP_MANAGED = 'data-umfi-rp-managed';
    const DATA_SCORING_MODEL = 'data-scoring-model';
    const DATA_SCORING_MODEL_RP_MANAGED = 'data-scoring-model-rp-managed';
    const TEXT_ENTRY_QTI_CLASS = 'textEntryInteraction';
    const PRIMARY_RESPONSE_IDENTIFIER = 'RESPONSE';
    const LEXICAL_GROUP_PREFIX = 'GROUP_';
    const GROUP_OUTCOME_SUFFIX = '_FOUND';
    const TEMP_SCORE_OUTCOME = synonymGroupGenerator.DEFAULT_TEMP_SCORE_OUTCOME;
    const FEATURE_DATA_ATTRS = [
        DATA_ITEM_TYPE,
        DATA_UMFI_VALUES,
        DATA_CASE_SENSITIVE,
        DATA_ALLOW_LEXICAL_FIELDS,
        DATA_MANAGED_OUTCOMES,
        DATA_RP_MANAGED,
        DATA_SCORING_MODEL,
        DATA_SCORING_MODEL_RP_MANAGED
    ];

    /**
     * @param {Object} textEntry
     * @returns {string|null}
     */
    const getTextEntryResponseIdentifier = function getTextEntryResponseIdentifier(textEntry) {
        if (!textEntry || !_.isFunction(textEntry.attr)) {
            return null;
        }

        return textEntry.attr('responseIdentifier') || null;
    };

    /**
     * @param {Object} textEntry
     * @returns {number|string|null}
     */
    const getTextEntrySerial = function getTextEntrySerial(textEntry) {
        if (!textEntry) {
            return null;
        }

        if (_.isFunction(textEntry.getSerial)) {
            return textEntry.getSerial();
        }

        return textEntry.serial;
    };

    /**
     * @param {Object} element
     * @returns {boolean}
     */
    const isTextEntryElement = function isTextEntryElement(element) {
        if (!element) {
            return false;
        }

        if (_.isFunction(element.is)) {
            return element.is(TEXT_ENTRY_QTI_CLASS);
        }

        return Element.isA(element, TEXT_ENTRY_QTI_CLASS) || element.qtiClass === TEXT_ENTRY_QTI_CLASS;
    };

    /**
     * @param {Object[]} elements
     * @returns {Object[]}
     */
    const collectTextEntries = function collectTextEntries(elements) {
        return _.filter(elements, isTextEntryElement);
    };

    /**
     * @param {Object} container
     * @returns {string}
     */
    const getContainerBodyString = function getContainerBodyString(container) {
        if (!container) {
            return '';
        }

        if (_.isFunction(container.body)) {
            const body = container.body();

            if (_.isString(body)) {
                return body;
            }
        }

        return _.isString(container.bdy) ? container.bdy : '';
    };

    /**
     * @param {Object} container
     * @returns {Object}
     */
    const getContainerElements = function getContainerElements(container) {
        if (!container) {
            return {};
        }

        if (_.isFunction(container.getElements)) {
            return container.getElements() || {};
        }

        return container.elements || {};
    };

    /**
     * Recurse nested containers/prompts using body placeholder order.
     *
     * @param {Object} container
     * @param {Object[]} acc
     * @param {Object} seen
     */
    const collectTextEntriesInDocumentOrder = function collectTextEntriesInDocumentOrder(container, acc, seen) {
        if (!container) {
            return;
        }

        const body = getContainerBodyString(container);
        const elements = getContainerElements(container);
        const visitElement = function visitElement(elt, serial) {
            if (!elt || (serial && seen[serial])) {
                return;
            }

            if (serial) {
                seen[serial] = true;
            }

            if (isTextEntryElement(elt)) {
                acc.push(elt);
            }

            if (_.isFunction(elt.getBody)) {
                collectTextEntriesInDocumentOrder(elt.getBody(), acc, seen);
            } else if (elt.elements || elt.bdy || _.isFunction(elt.body)) {
                collectTextEntriesInDocumentOrder(elt, acc, seen);
            }

            if (elt.prompt) {
                const promptBody = _.isFunction(elt.prompt.getBody)
                    ? elt.prompt.getBody()
                    : elt.prompt.bdy || elt.prompt;

                collectTextEntriesInDocumentOrder(promptBody, acc, seen);
            }
        };

        if (body) {
            const placeholderRe = /\{\{([^{}]+)\}\}/g;
            let match;

            while ((match = placeholderRe.exec(body)) !== null) {
                const serial = match[1];
                visitElement(elements[serial], serial);
            }

            return;
        }

        _.forEach(elements, (elt, serial) => {
            visitElement(elt, serial);
        });
    };

    /**
     * @param {Object} interaction
     * @returns {Object[]}
     */
    const getItemTextEntries = function getItemTextEntries(interaction) {
        const item = interaction && _.isFunction(interaction.getRootElement) ? interaction.getRootElement() : null;

        // Prefer model body placeholder order — that is what XML render uses.
        // Do not prefer raw DOM widget order: after insert-before, widget nodes can
        // still enumerate in creation order while body/XML already have the new first TEI.
        if (item && _.isFunction(item.getBody)) {
            const ordered = [];

            collectTextEntriesInDocumentOrder(item.getBody(), ordered, {});

            if (ordered.length) {
                return ordered;
            }
        }

        if (item && _.isFunction(item.getComposingElements)) {
            const textEntries = collectTextEntries(_.values(item.getComposingElements()));

            if (textEntries.length) {
                return textEntries;
            }
        }

        if (item && _.isFunction(item.getElements)) {
            const textEntries = collectTextEntries(_.values(item.getElements(TEXT_ENTRY_QTI_CLASS) || {}));

            if (textEntries.length) {
                return textEntries;
            }
        }

        if (isTextEntryElement(interaction)) {
            return [interaction];
        }

        return [];
    };

    /**
     * First textEntryInteraction in document order is the persistence anchor.
     *
     * @param {Object[]} textEntries
     * @returns {Object|null}
     */
    const getPrimaryTextEntry = function getPrimaryTextEntry(textEntries) {
        return textEntries.length ? textEntries[0] : null;
    };

    /**
     * @param {Object} textEntry
     * @returns {boolean}
     */
    const textEntryHasFeatureDataAttrs = function textEntryHasFeatureDataAttrs(textEntry) {
        if (!textEntry || !_.isFunction(textEntry.attr)) {
            return false;
        }

        return _.some(FEATURE_DATA_ATTRS, name => {
            const value = textEntry.attr(name);

            return !_.isUndefined(value) && value !== null && value !== '';
        });
    };

    /**
     * Move feature data-* attrs onto the first TEI; strip them from all others.
     * Covers insert-before: attrs stay on the old TEI until this runs.
     *
     * @param {Object} interaction
     * @returns {Object|null} primary text entry
     */
    const migrateFeatureDataAttributesToPrimary = function migrateFeatureDataAttributesToPrimary(interaction) {
        const textEntries = getItemTextEntries(interaction);
        const primaryTextEntry = getPrimaryTextEntry(textEntries);

        if (!primaryTextEntry) {
            return null;
        }

        const sourceTextEntry = _.find(textEntries, textEntryHasFeatureDataAttrs);

        if (sourceTextEntry && sourceTextEntry !== primaryTextEntry && _.isFunction(primaryTextEntry.attr)) {
            _.forEach(FEATURE_DATA_ATTRS, name => {
                const value = sourceTextEntry.attr(name);

                if (!_.isUndefined(value) && value !== null) {
                    primaryTextEntry.attr(name, value);
                }
            });
        }

        _.forEach(textEntries, textEntry => {
            if (textEntry === primaryTextEntry || !_.isFunction(textEntry.removeAttr)) {
                return;
            }

            _.forEach(FEATURE_DATA_ATTRS, name => {
                textEntry.removeAttr(name);
            });
        });

        return primaryTextEntry;
    };

    /**
     * @param {Object} interaction
     * @returns {boolean}
     */
    const isUmfiEnabled = function isUmfiEnabled(interaction) {
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);

        if (!primaryTextEntry || !_.isFunction(primaryTextEntry.attr)) {
            return false;
        }

        if (_.includes(UMFI_ITEM_TYPES, primaryTextEntry.attr(DATA_ITEM_TYPE))) {
            return true;
        }

        return parseDataUmfiValues(primaryTextEntry.attr(DATA_UMFI_VALUES)).length > 0;
    };

    /**
     * @param {Object} interaction
     * @returns {boolean}
     */
    const isAllowLexicalFieldsOnScoring = function isAllowLexicalFieldsOnScoring(interaction) {
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);

        return !!(primaryTextEntry && primaryTextEntry.attr(DATA_ALLOW_LEXICAL_FIELDS) === 'true');
    };

    /**
     * @param {Object} interaction
     * @param {boolean} enabled
     */
    const setUmfiEnabled = function setUmfiEnabled(interaction, enabled) {
        migrateFeatureDataAttributesToPrimary(interaction);
        const textEntries = getItemTextEntries(interaction);
        const primaryTextEntry = getPrimaryTextEntry(textEntries);

        if (!primaryTextEntry || !_.isFunction(primaryTextEntry.attr)) {
            return;
        }

        if (enabled) {
            primaryTextEntry.attr(
                DATA_ITEM_TYPE,
                primaryTextEntry.attr(DATA_ALLOW_LEXICAL_FIELDS) === 'true'
                    ? UMFI_OPEN_ITEM_TYPE
                    : UMFI_ITEM_TYPE
            );

            if (!primaryTextEntry.attr(DATA_UMFI_VALUES)) {
                primaryTextEntry.attr(DATA_UMFI_VALUES, '[]');
            }

            if (!primaryTextEntry.attr(DATA_CASE_SENSITIVE)) {
                primaryTextEntry.attr(DATA_CASE_SENSITIVE, 'false');
            }
        } else {
            clearUmfiResponseProcessing(interaction);
            _.forEach(textEntries, textEntry => {
                textEntry.removeAttr(DATA_ITEM_TYPE);
                textEntry.removeAttr(DATA_UMFI_VALUES);
                textEntry.removeAttr(DATA_CASE_SENSITIVE);
                textEntry.removeAttr(DATA_ALLOW_LEXICAL_FIELDS);
                textEntry.removeAttr(DATA_MANAGED_OUTCOMES);
                textEntry.removeAttr(DATA_RP_MANAGED);
            });
        }
    };

    /**
     * @param {string|null|undefined} jsonString
     * @returns {string[]}
     */
    const parseJsonStringArray = function parseJsonStringArray(jsonString) {
        if (!jsonString || !_.isString(jsonString)) {
            return [];
        }

        try {
            const parsed = JSON.parse(jsonString);

            return _.isArray(parsed) ? parsed : [];
        } catch (e) {
            return [];
        }
    };

    /**
     * @param {Object} interaction
     * @returns {string[]}
     */
    const getTextEntryResponseIdentifiers = function getTextEntryResponseIdentifiers(interaction) {
        return _.chain(getItemTextEntries(interaction))
            .map(textEntry => (_.isFunction(textEntry.attr) ? textEntry.attr('responseIdentifier') : null))
            .filter(Boolean)
            .uniq()
            .value();
    };

    /**
     * @param {Object[]} groups
     * @returns {Object[]}
     */
    const getScorableLexicalGroups = function getScorableLexicalGroups(groups) {
        return _.filter(normalizeLexicalGroups(groups), group => group.synonyms.length > 0);
    };

    /**
     * @param {Object} item
     * @returns {Object|null}
     */
    const ensureItemResponseProcessing = function ensureItemResponseProcessing(item) {
        if (!item) {
            return null;
        }

        if (item.responseProcessing) {
            return item.responseProcessing;
        }

        if (_.isFunction(item.createResponseProcessing)) {
            return item.createResponseProcessing();
        }

        return null;
    };

    /**
     * @param {Object} item
     * @param {string} xml
     */
    const updateCustomResponseProcessing = function updateCustomResponseProcessing(item, xml) {
        const rp = ensureItemResponseProcessing(item);

        if (!rp || !_.isString(xml) || !xml.trim()) {
            return;
        }

        if (_.isFunction(rp.setProcessingType)) {
            rp.setProcessingType('custom', xml);
        } else {
            rp.processingType = 'custom';
            rp.xml = xml;
        }
    };

    /**
     * @param {Object} item
     * @param {string} identifier
     * @param {Object} attributes
     * @param {number|null} [defaultValue]
     * @returns {Object}
     */
    const ensureOutcomeDeclaration = function ensureOutcomeDeclaration(item, identifier, attributes, defaultValue) {
        let outcome = item.getOutcomeDeclaration(identifier);

        if (!outcome) {
            outcome = item.createOutcomeDeclaration(_.clone(attributes));
            outcome.buildIdentifier(identifier, false);
        }

        if (!_.isUndefined(defaultValue) && _.isFunction(outcome.setDefaultValue)) {
            outcome.setDefaultValue(defaultValue);
        }

        return outcome;
    };

    /**
     * Parse data-scoring-model thresholds without importing scoringModelHelper
     * (avoids a circular AMD dependency).
     *
     * @param {string|null|undefined} raw
     * @returns {Array<{threshold: number, score: number}>}
     */
    const parseScoringModelThresholds = function parseScoringModelThresholds(raw) {
        if (!_.isString(raw) || !raw.trim()) {
            return [];
        }

        const trimmed = raw.trim();
        let parsed;

        try {
            parsed = JSON.parse(trimmed);
        } catch (e) {
            try {
                parsed = JSON.parse(trimmed.replace(/'/g, '"'));
            } catch (ignore) {
                return [];
            }
        }

        let pairs = [];

        if (_.isArray(parsed)) {
            pairs = parsed;
        } else if (_.isPlainObject(parsed)) {
            pairs = _.map(parsed, (score, threshold) => ({ threshold, score }));
        }

        return _(pairs)
            .map(entry => {
                const threshold = Number(_.isPlainObject(entry) ? entry.threshold : NaN);
                const score = Number(_.isPlainObject(entry) ? entry.score : NaN);

                if (!_.isFinite(threshold) || !_.isFinite(score)) {
                    return null;
                }

                return { threshold, score };
            })
            .compact()
            .sortBy(entry => -entry.threshold)
            .value();
    };

    /**
     * @param {Object} interaction
     * @returns {Array<{threshold: number, score: number}>}
     */
    const getScoringModelThresholds = function getScoringModelThresholds(interaction) {
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);

        if (!primaryTextEntry || !_.isFunction(primaryTextEntry.attr)) {
            return [];
        }

        return parseScoringModelThresholds(primaryTextEntry.attr(DATA_SCORING_MODEL));
    };

    /**
     * @param {Object} item
     * @param {Object} primaryTextEntry
     * @param {Object[]} groups
     * @param {number} maxScore
     * @param {Array<{threshold: number, score: number}>} [thresholds]
     */
    const syncOutcomeDeclarations = function syncOutcomeDeclarations(
        item,
        primaryTextEntry,
        groups,
        maxScore,
        thresholds
    ) {
        const desiredGroupIds = _.map(groups, 'id');
        const previousManaged = parseJsonStringArray(primaryTextEntry.attr(DATA_MANAGED_OUTCOMES));
        const useThresholds = _.isArray(thresholds) && thresholds.length > 0;

        _.forEach(previousManaged, id => {
            if (!_.includes(desiredGroupIds, id)) {
                item.removeOutcome(id);
            }
        });

        _.forEach(desiredGroupIds, id => {
            const groupOutcome = ensureOutcomeDeclaration(
                item,
                id,
                {
                    cardinality: 'single',
                    baseType: 'integer'
                },
                0
            );

            groupOutcome.attr('normalMinimum', 0);
            groupOutcome.attr('normalMaximum', 1);
        });

        if (useThresholds) {
            const tempScore = ensureOutcomeDeclaration(
                item,
                TEMP_SCORE_OUTCOME,
                {
                    cardinality: 'single',
                    baseType: 'float'
                },
                0
            );

            if (tempScore && _.isFunction(tempScore.attr)) {
                tempScore.attr('normalMinimum', 0);
            }
        } else {
            item.removeOutcome(TEMP_SCORE_OUTCOME);
        }

        const scoreOutcome = ensureOutcomeDeclaration(
            item,
            'SCORE',
            {
                cardinality: 'single',
                baseType: 'float'
            },
            0
        );

        scoreOutcome.attr('normalMinimum', 0);
        scoreOutcome.attr('normalMaximum', maxScore);

        ensureOutcomeDeclaration(
            item,
            'MAXSCORE',
            {
                cardinality: 'single',
                baseType: 'float'
            },
            maxScore
        );

        primaryTextEntry.attr(DATA_MANAGED_OUTCOMES, JSON.stringify(desiredGroupIds));
    };

    /**
     * @param {Object} primaryTextEntry
     */
    const stripInternalAuthoringAttrs = function stripInternalAuthoringAttrs(primaryTextEntry) {
        if (!primaryTextEntry || !_.isFunction(primaryTextEntry.removeAttr)) {
            return;
        }

        primaryTextEntry.removeAttr(DATA_MANAGED_OUTCOMES);
        primaryTextEntry.removeAttr(DATA_RP_MANAGED);
    };

    /**
     * @param {Object} interaction
     */
    const ensureUmfiResponseTemplates = function ensureUmfiResponseTemplates(interaction) {
        if (!isUmfiEnabled(interaction)) {
            return;
        }

        _.forEach(getItemTextEntries(interaction), textEntry => {
            if (!_.isFunction(textEntry.getResponseDeclaration)) {
                return;
            }

            const response = textEntry.getResponseDeclaration();

            if (response && _.isFunction(response.setTemplate)) {
                response.setTemplate('CUSTOM');
            }
        });
    };

    /**
     * Push each text `_container` body from the live editor DOM into the model
     * so placeholder order matches what the author sees before migrate/save.
     * Only applies when the serialized body still references every current TEI.
     *
     * @param {Object} item
     */
    const syncTextContainersFromDom = function syncTextContainersFromDom(item) {
        if (!item || !_.isFunction(item.getComposingElements) || typeof $ === 'undefined') {
            return;
        }

        _.forEach(item.getComposingElements() || {}, elt => {
            if (!Element.isA(elt, '_container') || !_.isFunction(elt.body) || !_.isFunction(elt.data)) {
                return;
            }

            const widget = elt.data('widget');

            if (!widget || !widget.$container || !widget.$container.length) {
                return;
            }

            const $editable = widget.$container.find('[data-html-editable]').first();

            if (!$editable.length) {
                return;
            }

            const editor = $editable.data('editor');
            const html =
                editor && _.isFunction(editor.getData) ? editor.getData() : $editable.html();

            if (!_.isString(html)) {
                return;
            }

            const newBody = contentHelper.getContent($('<div>').html(html));
            const currentElements = _.isFunction(elt.getElements) ? elt.getElements() : elt.elements || {};
            const textEntrySerials = _.keys(currentElements).filter(serial =>
                isTextEntryElement(currentElements[serial])
            );
            const keepsAllTextEntries = _.every(
                textEntrySerials,
                serial => newBody.indexOf('{{' + serial + '}}') !== -1
            );

            if (!keepsAllTextEntries) {
                return;
            }

            if (newBody !== elt.body()) {
                elt.body(newBody);
            }
        });
    };

    /**
     * @param {Object} item
     */
    const ensurePersistedBeforeSave = function ensurePersistedBeforeSave(item) {
        const sampleInteraction = {
            getRootElement: function getRootElement() {
                return item;
            }
        };

        // Align model placeholder order with the editor, then re-anchor feature data-*.
        syncTextContainersFromDom(item);
        migrateFeatureDataAttributesToPrimary(sampleInteraction);

        const primaryTextEntry = getPrimaryTextEntry(getItemTextEntries(sampleInteraction));

        if (!primaryTextEntry) {
            return;
        }

        const config = getEvaluationConfig(sampleInteraction);

        if (!config.evaluateAsUmfi) {
            return;
        }

        // Re-serialize so legacy payloads (e.g. [["apple"]]) become the current
        // object shape before response processing is regenerated.
        persistEvaluationConfig(sampleInteraction, {
            evaluateAsUmfi: true,
            lexicalGroups: config.lexicalGroups,
            caseSensitive: config.caseSensitive,
            allowLexicalFieldsOnScoring: config.allowLexicalFieldsOnScoring
        });
    };

    /**
     * @param {Object} item
     * @param {Object} primaryTextEntry
     * @returns {string[]}
     */
    const getManagedGroupOutcomeIds = function getManagedGroupOutcomeIds(item, primaryTextEntry) {
        const fromManagedAttr = parseJsonStringArray(primaryTextEntry.attr(DATA_MANAGED_OUTCOMES));
        const fromUmfiValues = _.map(parseDataUmfiValues(primaryTextEntry.attr(DATA_UMFI_VALUES)), 'id');

        return _.uniq(_.filter(fromManagedAttr.concat(fromUmfiValues), Boolean));
    };

    /**
     * @param {Object} item
     */
    const resetScoreOutcomeBounds = function resetScoreOutcomeBounds(item) {
        const scoreOutcome = item.getOutcomeDeclaration('SCORE');

        if (!scoreOutcome) {
            return;
        }

        if (_.isFunction(scoreOutcome.removeAttr)) {
            scoreOutcome.removeAttr('normalMinimum');
            scoreOutcome.removeAttr('normalMaximum');
            return;
        }

        if (_.isFunction(scoreOutcome.attr)) {
            scoreOutcome.attr('normalMinimum', undefined);
            scoreOutcome.attr('normalMaximum', undefined);
        }
    };

    /**
     * @param {Object} interaction
     */
    const clearUmfiResponseProcessing = function clearUmfiResponseProcessing(interaction) {
        const item = interaction.getRootElement();
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);

        if (!item || !primaryTextEntry) {
            return;
        }

        const wasRpManaged =
            primaryTextEntry.attr(DATA_RP_MANAGED) === 'true' ||
            isUmfiEnabled(interaction) ||
            parseDataUmfiValues(primaryTextEntry.attr(DATA_UMFI_VALUES)).length > 0;

        _.forEach(getManagedGroupOutcomeIds(item, primaryTextEntry), id => {
            item.removeOutcome(id);
        });

        if (wasRpManaged) {
            const rp = item.responseProcessing;

            if (rp && _.isFunction(rp.setProcessingType) && rp.processingType === 'custom') {
                rp.setProcessingType('templateDriven');
            } else if (rp) {
                rp.processingType = 'templateDriven';
            }

            if (rp) {
                rp.xml = '';
            }

            item.removeOutcome('MAXSCORE');
            item.removeOutcome(TEMP_SCORE_OUTCOME);
            resetScoreOutcomeBounds(item);
        }

        primaryTextEntry.removeAttr(DATA_MANAGED_OUTCOMES);
        primaryTextEntry.removeAttr(DATA_RP_MANAGED);
    };

    /**
     * @param {Object} interaction
     * @param {{evaluateAsUmfi?: boolean, lexicalGroups?: Object[]}} config
     */
    const syncResponseProcessing = function syncResponseProcessing(interaction, config) {
        const item = interaction && _.isFunction(interaction.getRootElement) ? interaction.getRootElement() : null;
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);
        const lexicalGroups =
            config && config.lexicalGroups ? normalizeLexicalGroups(config.lexicalGroups) : getLexicalGroups(interaction);
        const scorableGroups = getScorableLexicalGroups(lexicalGroups);

        if (!item || !primaryTextEntry || !isUmfiEnabled(interaction)) {
            return;
        }

        if (!scorableGroups.length) {
            const previousManaged = parseJsonStringArray(primaryTextEntry.attr(DATA_MANAGED_OUTCOMES));

            _.forEach(previousManaged, id => {
                item.removeOutcome(id);
            });

            primaryTextEntry.attr(DATA_MANAGED_OUTCOMES, '[]');

            if (primaryTextEntry.attr(DATA_RP_MANAGED) === 'true') {
                const rp = item.responseProcessing;

                if (rp && _.isFunction(rp.setProcessingType) && rp.processingType === 'custom') {
                    rp.setProcessingType('templateDriven');
                } else if (rp) {
                    rp.processingType = 'templateDriven';
                }

                if (rp) {
                    rp.xml = '';
                }

                item.removeOutcome('MAXSCORE');
                item.removeOutcome(TEMP_SCORE_OUTCOME);
                resetScoreOutcomeBounds(item);
                primaryTextEntry.removeAttr(DATA_RP_MANAGED);
            }

            return;
        }

        const responseIdentifiers = getTextEntryResponseIdentifiers(interaction);

        if (!responseIdentifiers.length) {
            return;
        }

        const thresholds = getScoringModelThresholds(interaction);
        const rpConfig = synonymGroupGenerator.normalizeConfig({
            interactions: responseIdentifiers,
            synonymGroups: _.map(scorableGroups, group => ({
                id: group.id,
                label: group.identifier,
                synonyms: group.synonyms
            })),
            caseSensitive: isCaseSensitive(interaction),
            thresholds
        });

        synonymGroupGenerator.validateConfig(rpConfig);

        const rpXml = synonymGroupGenerator.generateResponseProcessing(rpConfig);
        const maxScore = synonymGroupGenerator.getMaxScore(rpConfig);

        updateCustomResponseProcessing(item, rpXml);
        ensureUmfiResponseTemplates(interaction);
        primaryTextEntry.attr(DATA_RP_MANAGED, 'true');
        syncOutcomeDeclarations(item, primaryTextEntry, scorableGroups, maxScore, thresholds);
    };

    /**
     * @param {number} index
     * @returns {string}
     */
    const buildDefaultLexicalGroupIdentifier = function buildDefaultLexicalGroupIdentifier(index) {
        return `${LEXICAL_GROUP_PREFIX}${index + 1}`;
    };

    /**
     * Outcome declaration id derived from a lexical-field identifier.
     * Appends `_FOUND` when missing (GROUP_1 → GROUP_1_FOUND).
     *
     * @param {string} identifier
     * @returns {string}
     */
    const buildGroupOutcomeId = function buildGroupOutcomeId(identifier) {
        const normalized = String(identifier || '')
            .trim()
            .replace(/[^a-zA-Z0-9]+/g, '_')
            .replace(/^_+|_+$/g, '')
            .toUpperCase();

        if (!normalized) {
            return '';
        }

        if (normalized.endsWith(GROUP_OUTCOME_SUFFIX)) {
            return normalized;
        }

        return `${normalized}${GROUP_OUTCOME_SUFFIX}`;
    };

    /**
     * Strip trailing `_FOUND` when recovering a UI identifier from a stored outcome id.
     *
     * @param {string} value
     * @returns {string}
     */
    const stripGroupOutcomeSuffix = function stripGroupOutcomeSuffix(value) {
        const normalized = String(value || '').trim();

        if (!normalized.endsWith(GROUP_OUTCOME_SUFFIX)) {
            return normalized;
        }

        return normalized.slice(0, -GROUP_OUTCOME_SUFFIX.length);
    };

    /**
     * @param {Array<{identifier?: string}>} [groups]
     * @returns {string}
     */
    const buildNextLexicalGroupIdentifier = function buildNextLexicalGroupIdentifier(groups) {
        const normalized = normalizeLexicalGroups(groups || []);
        const usedIdentifiers = _.map(normalized, 'identifier');
        let index = 0;
        let identifier = buildDefaultLexicalGroupIdentifier(index);

        while (_.includes(usedIdentifiers, identifier)) {
            index += 1;
            identifier = buildDefaultLexicalGroupIdentifier(index);
        }

        return identifier;
    };

    /**
     * @param {string[]} values
     * @returns {string[]}
     */
    const normalizeVariantList = function normalizeVariantList(values) {
        return _.chain(values || [])
            .map(String)
            .map(value => value.trim())
            .filter(Boolean)
            .value();
    };

    /**
     * @param {string} value
     * @param {boolean} [caseSensitive=false]
     * @returns {string}
     */
    const normalizeVariantForCompare = function normalizeVariantForCompare(value, caseSensitive) {
        const trimmed = String(value || '').trim();

        return caseSensitive ? trimmed : trimmed.toLowerCase();
    };

    /**
     * @param {string[]} variants
     * @param {string} candidate
     * @param {boolean} [caseSensitive=false]
     * @returns {boolean}
     */
    const hasLexicalVariant = function hasLexicalVariant(variants, candidate, caseSensitive) {
        const needle = normalizeVariantForCompare(candidate, caseSensitive);

        if (!needle) {
            return false;
        }

        return _.some(
            variants || [],
            variant => normalizeVariantForCompare(variant, caseSensitive) === needle
        );
    };

    /**
     * @param {Array<{id?: string, group?: string, identifier?: string, label?: string, canonical?: string, synonyms?: string[], variants?: string[], collapsed?: boolean}>} groups
     * @returns {Array<{id: string, identifier: string, canonical: string, synonyms: string[], collapsed: boolean}>}
     */
    const normalizeLexicalGroups = function normalizeLexicalGroups(groups) {
        const usedIdentifiers = {};
        const usedOutcomeIds = {};

        return _.map(groups || [], (group, index) => {
            const explicitCanonical = String(group.canonical || '').trim();
            const rawSynonyms = normalizeVariantList(group.synonyms || group.variants || []);
            const synonyms = explicitCanonical
                ? _.uniq([explicitCanonical].concat(rawSynonyms))
                : rawSynonyms;
            // Prefer an existing authoring identifier (legacy or previously assigned);
            // otherwise allocate GROUP_n. Do not rename with _FOUND here.
            const requestedIdentifier = String(
                group.identifier || group.groupIdentifier || group.label || ''
            ).trim();
            let identifier = requestedIdentifier || buildDefaultLexicalGroupIdentifier(index);
            let identifierIndex = index;

            while (usedIdentifiers[identifier]) {
                identifier = buildDefaultLexicalGroupIdentifier(identifierIndex);
                identifierIndex += 1;
            }

            usedIdentifiers[identifier] = true;

            // _FOUND is applied here for the outcome id stored in data-umfi-values.group.
            let id =
                buildGroupOutcomeId(group.id || group.group || identifier) ||
                buildGroupOutcomeId(identifier);
            let suffix = 1;
            const outcomeBase = id.replace(new RegExp(`${GROUP_OUTCOME_SUFFIX}$`), '');

            while (usedOutcomeIds[id]) {
                id = `${outcomeBase}_${suffix}${GROUP_OUTCOME_SUFFIX}`;
                suffix += 1;
            }

            usedOutcomeIds[id] = true;

            return {
                id,
                identifier,
                // Prefer explicit canonical when provided; otherwise first synonym.
                canonical: explicitCanonical || synonyms[0] || '',
                synonyms,
                draftVariant: !!group.draftVariant
            };
        });
    };

    /**
     * @param {*} entry
     * @returns {{identifier: string, canonical?: string, synonyms: string[]}}
     */
    const mapDataUmfiEntry = function mapDataUmfiEntry(entry) {
        if (_.isObject(entry) && !_.isArray(entry)) {
            const canonical = String(entry.canonical || '').trim();
            const variants = normalizeVariantList(entry.variants || entry.synonyms || []);
            const storedGroup = String(
                entry.group || entry.id || entry.identifier || entry.groupIdentifier || ''
            ).trim();
            const legacyLabel = _.isString(entry.label) ? entry.label.trim() : '';
            // `group` is the RP/outcome identifier (*_FOUND); strip for authoring identifier.
            const identifier = stripGroupOutcomeSuffix(storedGroup) || legacyLabel;

            return {
                identifier,
                id: identifier ? buildGroupOutcomeId(identifier) : '',
                canonical,
                synonyms: canonical ? _.uniq([canonical].concat(variants)) : variants
            };
        }

        const synonyms = normalizeVariantList(entry);

        return {
            identifier: '',
            canonical: synonyms[0] || '',
            synonyms
        };
    };

    /**
     * @param {string|null|undefined} jsonString
     * @returns {Array<{identifier: string, canonical: string, synonyms: string[]}>}
     */
    const parseDataUmfiValues = function parseDataUmfiValues(jsonString) {
        if (!jsonString || !_.isString(jsonString)) {
            return [];
        }

        try {
            const parsed = JSON.parse(jsonString);

            if (parsed && typeof parsed === 'object' && !_.isArray(parsed)) {
                return normalizeLexicalGroups(
                    _.map(parsed, (variants, identifier) => ({
                        identifier: String(identifier),
                        synonyms: _.isArray(variants) ? variants : []
                    }))
                );
            }

            if (_.isArray(parsed)) {
                return normalizeLexicalGroups(_.map(parsed, mapDataUmfiEntry));
            }

            return [];
        } catch (e) {
            return [];
        }
    };

    /**
     * @param {Array<{identifier?: string, synonyms: string[]}>} groups
     * @returns {string}
     */
    const serializeDataUmfiValues = function serializeDataUmfiValues(groups) {
        const payload = _.chain(normalizeLexicalGroups(groups))
            .map(group => {
                const synonyms = normalizeVariantList(group.synonyms);

                if (!synonyms.length) {
                    return null;
                }

                return {
                    // RP/outcome identifier so data-umfi-values.group matches response processing.
                    group: group.id || buildGroupOutcomeId(group.identifier),
                    canonical: group.canonical || synonyms[0],
                    variants: synonyms
                };
            })
            .filter(Boolean)
            .value();

        return JSON.stringify(payload);
    };

    /**
     * @param {Object} interaction
     * @returns {Object|null}
     */
    const getPrimaryTextEntryForInteraction = function getPrimaryTextEntryForInteraction(interaction) {
        migrateFeatureDataAttributesToPrimary(interaction);

        return getPrimaryTextEntry(getItemTextEntries(interaction));
    };

    /**
     * @param {Object} interaction
     * @returns {Array<{id: string, label: string, synonyms: string[], collapsed: boolean}>}
     */
    const getLexicalGroups = function getLexicalGroups(interaction) {
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);

        if (!primaryTextEntry) {
            return [];
        }

        return parseDataUmfiValues(primaryTextEntry.attr(DATA_UMFI_VALUES));
    };

    /**
     * @param {Object} interaction
     * @returns {boolean}
     */
    const isCaseSensitive = function isCaseSensitive(interaction) {
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);

        return !!(primaryTextEntry && primaryTextEntry.attr(DATA_CASE_SENSITIVE) === 'true');
    };

    /**
     * @param {Object} interaction
     * @param {Array<{label?: string, synonyms: string[], collapsed?: boolean}>} groups
     */
    const setLexicalGroups = function setLexicalGroups(interaction, groups) {
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);

        if (!primaryTextEntry || !_.isFunction(primaryTextEntry.attr)) {
            return;
        }

        primaryTextEntry.attr(DATA_UMFI_VALUES, serializeDataUmfiValues(groups));
    };

    /**
     * @param {Object} interaction
     * @param {boolean} enabled
     */
    const setCaseSensitive = function setCaseSensitive(interaction, enabled) {
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);

        if (!primaryTextEntry || !_.isFunction(primaryTextEntry.attr)) {
            return;
        }

        if (enabled) {
            primaryTextEntry.attr(DATA_CASE_SENSITIVE, 'true');
        } else {
            primaryTextEntry.attr(DATA_CASE_SENSITIVE, 'false');
        }
    };

    /**
     * @param {Object} interaction
     * @returns {{evaluateAsUmfi: boolean, allowLexicalFieldsOnScoring: boolean, caseSensitive: boolean, lexicalGroups: Object[]}}
     */
    const getEvaluationConfig = function getEvaluationConfig(interaction) {
        return {
            evaluateAsUmfi: isUmfiEnabled(interaction),
            allowLexicalFieldsOnScoring: isAllowLexicalFieldsOnScoring(interaction),
            caseSensitive: isCaseSensitive(interaction),
            lexicalGroups: getLexicalGroups(interaction)
        };
    };

    /**
     * @param {Object} interaction
     * @param {{evaluateAsUmfi?: boolean, allowLexicalFieldsOnScoring?: boolean, caseSensitive?: boolean, lexicalGroups?: Object[]}} config
     */
    const persistEvaluationConfig = function persistEvaluationConfig(interaction, config) {
        migrateFeatureDataAttributesToPrimary(interaction);

        if (config.evaluateAsUmfi === false) {
            setUmfiEnabled(interaction, false);
            return;
        }

        if (config.evaluateAsUmfi === true) {
            setUmfiEnabled(interaction, true);
        }

        if (!_.isUndefined(config.lexicalGroups)) {
            setLexicalGroups(interaction, config.lexicalGroups);
        }

        if (!_.isUndefined(config.caseSensitive)) {
            setCaseSensitive(interaction, config.caseSensitive);
        }

        if (!_.isUndefined(config.allowLexicalFieldsOnScoring)) {
            setAllowLexicalFieldsOnScoring(interaction, config.allowLexicalFieldsOnScoring);
        }

        syncResponseProcessing(interaction, {
            evaluateAsUmfi: isUmfiEnabled(interaction),
            lexicalGroups: getLexicalGroups(interaction)
        });
    };

    /**
     * @param {Object} interaction
     * @param {boolean} enabled
     */
    const setAllowLexicalFieldsOnScoring = function setAllowLexicalFieldsOnScoring(interaction, enabled) {
        const primaryTextEntry = getPrimaryTextEntryForInteraction(interaction);

        if (!primaryTextEntry || !_.isFunction(primaryTextEntry.attr)) {
            return;
        }

        if (!isUmfiEnabled(interaction)) {
            return;
        }

        if (enabled) {
            primaryTextEntry.attr(DATA_ALLOW_LEXICAL_FIELDS, 'true');
            primaryTextEntry.attr(DATA_ITEM_TYPE, UMFI_OPEN_ITEM_TYPE);
        } else {
            primaryTextEntry.removeAttr(DATA_ALLOW_LEXICAL_FIELDS);

            if (isUmfiEnabled(interaction)) {
                primaryTextEntry.attr(DATA_ITEM_TYPE, UMFI_ITEM_TYPE);
            }
        }
    };

    return {
        UMFI_ITEM_TYPE,
        PRIMARY_RESPONSE_IDENTIFIER,
        DATA_ITEM_TYPE,
        DATA_UMFI_VALUES,
        DATA_CASE_SENSITIVE,
        DATA_ALLOW_LEXICAL_FIELDS,
        DATA_MANAGED_OUTCOMES,
        DATA_RP_MANAGED,
        getItemTextEntries,
        getPrimaryTextEntry,
        migrateFeatureDataAttributesToPrimary,
        FEATURE_DATA_ATTRS,
        syncTextContainersFromDom,
        getTextEntrySerial,
        getTextEntryResponseIdentifier,
        getTextEntryResponseIdentifiers,
        isUmfiEnabled,
        isAllowLexicalFieldsOnScoring,
        isCaseSensitive,
        getLexicalGroups,
        getEvaluationConfig,
        getScorableLexicalGroups,
        normalizeLexicalGroups,
        hasLexicalVariant,
        parseDataUmfiValues,
        serializeDataUmfiValues,
        buildDefaultLexicalGroupIdentifier,
        buildNextLexicalGroupIdentifier,
        buildGroupOutcomeId,
        LEXICAL_GROUP_PREFIX,
        GROUP_OUTCOME_SUFFIX,
        setUmfiEnabled,
        setAllowLexicalFieldsOnScoring,
        setLexicalGroups,
        setCaseSensitive,
        syncResponseProcessing,
        clearUmfiResponseProcessing,
        persistEvaluationConfig,
        stripInternalAuthoringAttrs,
        ensureUmfiResponseTemplates,
        ensurePersistedBeforeSave
    };
});
