define(function(){
    return {
        name: 'xmlRenderer',
        locations : {
            '_container' : 'taoQtiXmlRenderer/renderers/Container',
            'assessmentItem' : 'taoQtiXmlRenderer/renderers/Item',
            'stylesheet' : 'taoQtiXmlRenderer/renderers/Stylesheet',
            'responseDeclaration' : 'taoQtiXmlRenderer/renderers/ResponseDeclaration',
            'outcomeDeclaration' : 'taoQtiXmlRenderer/renderers/OutcomeDeclaration',
            'responseProcessing' : 'taoQtiXmlRenderer/renderers/ResponseProcessing',
            '_simpleFeedbackRule' : 'taoQtiXmlRenderer/renderers/responses/SimpleFeedbackRule',
            'math' : 'taoQtiXmlRenderer/renderers/Math',
            'object' : 'taoQtiXmlRenderer/renderers/Object',
            'modalFeedback' : 'taoQtiXmlRenderer/renderers/feedbacks/ModalFeedback',
            'rubricBlock' : 'taoQtiXmlRenderer/renderers/RubricBlock',
            'associateInteraction' : 'taoQtiXmlRenderer/renderers/interactions/AssociateInteraction',
            'choiceInteraction' : 'taoQtiXmlRenderer/renderers/interactions/ChoiceInteraction',
            'extendedTextInteraction' : 'taoQtiXmlRenderer/renderers/interactions/ExtendedTextInteraction',
            'gapMatchInteraction' : 'taoQtiXmlRenderer/renderers/interactions/GapMatchInteraction',
            'graphicAssociateInteraction' : 'taoQtiXmlRenderer/renderers/interactions/GraphicAssociateInteraction',
            'graphicGapMatchInteraction' : 'taoQtiXmlRenderer/renderers/interactions/GraphicGapMatchInteraction',
            'graphicOrderInteraction' : 'taoQtiXmlRenderer/renderers/interactions/GraphicOrderInteraction',
            'hotspotInteraction' : 'taoQtiXmlRenderer/renderers/interactions/HotspotInteraction',
            'hottextInteraction' : 'taoQtiXmlRenderer/renderers/interactions/HottextInteraction',
            'inlineChoiceInteraction' : 'taoQtiXmlRenderer/renderers/interactions/InlineChoiceInteraction',
            'matchInteraction' : 'taoQtiXmlRenderer/renderers/interactions/MatchInteraction',
            'mediaInteraction' : 'taoQtiXmlRenderer/renderers/interactions/MediaInteraction',
            'orderInteraction' : 'taoQtiXmlRenderer/renderers/interactions/OrderInteraction',
            'selectPointInteraction' : 'taoQtiXmlRenderer/renderers/interactions/SelectPointInteraction',
            'sliderInteraction' : 'taoQtiXmlRenderer/renderers/interactions/SliderInteraction',
            'textEntryInteraction' : 'taoQtiXmlRenderer/renderers/interactions/TextEntryInteraction',
            'uploadInteraction' : 'taoQtiXmlRenderer/renderers/interactions/UploadInteraction',
            'prompt' : 'taoQtiXmlRenderer/renderers/interactions/Prompt',
            'associableHotspot' : 'taoQtiXmlRenderer/renderers/choices/AssociableHotspot',
            'gap' : 'taoQtiXmlRenderer/renderers/choices/Gap',
            'gapImg' : 'taoQtiXmlRenderer/renderers/choices/GapImg',
            'gapText' : 'taoQtiXmlRenderer/renderers/choices/GapText',
            'hotspotChoice' : 'taoQtiXmlRenderer/renderers/choices/HotspotChoice',
            'hottext' : 'taoQtiXmlRenderer/renderers/choices/Hottext',
            'inlineChoice' : 'taoQtiXmlRenderer/renderers/choices/InlineChoice',
            'simpleAssociableChoice' : 'taoQtiXmlRenderer/renderers/choices/SimpleAssociableChoice',
            'simpleChoice' : 'taoQtiXmlRenderer/renderers/choices/SimpleChoice'
        }
    };
});