define([], function(){
    return {
        'assessmentItem' : 'taoQtiItem/core/Item',
        'responseProcessing' : 'taoQtiItem/core/ResponseProcessing',
        'stylesheet' : 'taoQtiItem/core/Stylesheet',
        'math' : 'taoQtiItem/core/Math',
        'object' : 'taoQtiItem/core/Object',
        'outcomeDeclaration' : 'taoQtiItem/core/variables/OutcomeDeclaration',
        'responseDeclaration' : 'taoQtiItem/core/variables/ResponseDeclaration',
        'rubricBlock' : 'taoQtiItem/core/RubricBlock',
        'associableHotspot' : 'taoQtiItem/core/choices/AssociableHotspot',
        'gap' : 'taoQtiItem/core/choices/Gap',
        'gapImg' : 'taoQtiItem/core/choices/GapImg',
        'gapText' : 'taoQtiItem/core/choices/GapText',
        'hotspotChoice' : 'taoQtiItem/core/choices/HotspotChoice',
        'hottext' : 'taoQtiItem/core/choices/Hottext',
        'inlineChoice' : 'taoQtiItem/core/choices/InlineChoice',
        'simpleAssociableChoice' : 'taoQtiItem/core/choices/SimpleAssociableChoice',
        'simpleChoice' : 'taoQtiItem/core/choices/SimpleChoice',
        'associateInteraction' : 'taoQtiItem/core/interactions/AssociateInteraction',
        'choiceInteraction' : 'taoQtiItem/core/interactions/ChoiceInteraction',
        'endAttemptInteraction' : 'taoQtiItem/core/interactions/EndAttemptInteraction',
        'extendedTextInteraction' : 'taoQtiItem/core/interactions/ExtendedTextInteraction',
        'gapMatchInteraction' : 'taoQtiItem/core/interactions/GapMatchInteraction',
        'graphicAssociateInteraction' : 'taoQtiItem/core/interactions/GraphicAssociateInteraction',
        'graphicGapMatchInteraction' : 'taoQtiItem/core/interactions/GraphicGapMatchInteraction',
        'graphicOrderInteraction' : 'taoQtiItem/core/interactions/GraphicOrderInteraction',
        'hotspotInteraction' : 'taoQtiItem/core/interactions/HotspotInteraction',
        'hottextInteraction' : 'taoQtiItem/core/interactions/HottextInteraction',
        'inlineChoiceInteraction' : 'taoQtiItem/core/interactions/InlineChoiceInteraction',
        'matchInteraction' : 'taoQtiItem/core/interactions/MatchInteraction',
        'mediaInteraction' : 'taoQtiItem/core/interactions/MediaInteraction',
        'orderInteraction' : 'taoQtiItem/core/interactions/OrderInteraction',
        'prompt' : 'taoQtiItem/core/interactions/Prompt',
        'selectPointInteraction' : 'taoQtiItem/core/interactions/SelectPointInteraction',
        'sliderInteraction' : 'taoQtiItem/core/interactions/SliderInteraction',
        'textEntryInteraction' : 'taoQtiItem/core/interactions/TextEntryInteraction',
        'uploadInteraction' : 'taoQtiItem/core/interactions/UploadInteraction',
        'feedbackBlock' : 'taoQtiItem/core/feedbacks/FeedbackBlock',
        'feedbackInline' : 'taoQtiItem/core/feedbacks/FeedbackInline',
        'modalFeedback' : 'taoQtiItem/core/feedbacks/ModalFeedback'
    };
});